### PR TITLE
Extensions Cleanup

### PR DESCRIPTION
**Pull request by anthonydresser**
Quite a large PR, would recommend using the w=1 http argument ot remove white space changes.
- Removes account-provider back to its own extension
- Moves extension-modules to a extensions level requirement
- adds .vscodeignore and .npmignores to extension to reduce the amount of files they copy over during compile/bundling.
- adds and updated npm-shrinkwraps throughout the code base
- Changes some of the export methods of the extension modules to support the new folder layout of the extensions folder.

Overall this remove ~500 files from bundled package while also moving the account-provider back to it's own extension (the 2 goals of this PR)

### CODE REVIEW

**Comment by kburtram** [comment]
@anthonydresser how many files would we save if we don't move account-provider to a separate extension but keep all the other changes in the PR.  Basically we're at ~13800 files and VS Code is around ~5500, so we still have a lot of files we need to eliminate to get even close to our baseline.  After this change if account-provider is still containing a lot of duplicate files with mssql we'll need to consider merging it again, so we should understand this impact now to make the correct decision.

**Comment by anthonydresser** [comment]
@kburtram after doing the other optimization I made, combining the two extensions provide next to no safe in files. You only save in metadata files like package.json and shrinkwrap. So it saves maybe ~10 files.

**Comment by kburtram** [comment]
@anthonydresser thanks for making this refactor!  As long as duplication is less than ~100 files or so I agree having separate extensions (correct decoupling) is worth the additional bloat.

**Comment by kburtram** [comment]
@anthonydresser @AbbiePetcht thinks this may fix https://github.com/Microsoft/sqlopsstudio/issues/370.  Are you waiting on anything to merge (so we can verify if it fixes or not)?

**Comment by anthonydresser** [comment]
I'll work on getting this in tonight, I want to double check nothing breaks functionally since it hits a lot of core code for the extensions

**Comment by AbbiePetcht** [comment]
I just verified the Azure icons. It fixes the issue

---
In reply to: [352921659](https://github.com/Microsoft/sqlopsstudio/pull/359#issuecomment-352921659) [](ancestors = 352921659)

**Pull request merged**
