### PR TITLE
Number of rows affected/queried

### PR DESCRIPTION
**Pull request by grishRodCas**
Please make the number of rows affected/queried appear in the bottom bar, just like SQL Management Studio does.... and/or remember manual changes if the same query is re-run.

image

### CODE REVIEW

**Comment by kburtram** [comment]
@grishRodCas could you please add a screenshot or two highlighting the UI that's being changed?  That's really helpful to visualize what the code changes are doing.  Thanks!

**Comment by anthonydresser** [comment]
@grishRodCas it looks like you didn't choose the right branches to merge.  The base branch of the merge should be master of this repo and the compare branch should be which ever branch you have your changes on in your fork.

**Comment by grishRodCas** [comment]
Here it is the screenshot you asked
Thanks!

[cid:image001.png@01D40A61.7889A8A0]

De: Karl Burtram <notifications@github.com>
Enviado el: viernes, 22 de junio de 2018 03:28 p. m.
Para: Microsoft/sqlopsstudio <sqlopsstudio@noreply.github.com>
CC: grishRodCas <jesus.rodcas@outlook.com>; Mention <mention@noreply.github.com>
Asunto: Re: [Microsoft/sqlopsstudio] Number of rows affected/queried (#1714)


@grishRodCas<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FgrishRodCas&data=02%7C01%7C%7Ca1eff01e2c0b4b88f1a108d5d87eacdb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636652960929594033&sdata=cHH1n0Fu9CLcdltMt4Gp5CCSwl0qkJMIYXuwBO0hir8%3D&reserved=0> could you please add a screenshot or two highlighting the UI that's being changed? That's really helpful to visualize what the code changes are doing. Thanks!

**Comment by kburtram** [comment]
@grishRodCas thanks for the screenshot?  Could you please clarify if this PR is supposed to add the feature you're proposing?  Or are you trying to suggest we add the feature?

If the PR contains the implementation of the feature could you please rebase or merge `master` so that only you're changes are included in the diff?  If this is for suggestion purposes then we can track the request through this issue https://github.com/Microsoft/sqlopsstudio/issues/1713.  Thanks!

**Comment by grishRodCas** [comment]
Sorry, this ticket is only this is for suggestion purposes


De: Karl Burtram
Enviado: lunes, 25 de junio 2:55 PM
Asunto: Re: [Microsoft/sqlopsstudio] Number of rows affected/queried (#1714)
Para: Microsoft/sqlopsstudio
Cc: grishRodCas, Mention


@grishRodCas<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FgrishRodCas&data=02%7C01%7C%7C7579ecea4da545063ec408d5dad5955c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636655533219023159&sdata=IvGIxZ2fp3roKyDUu4lbHPjsuV0fuIcsYpEj%2BSA3iWI%3D&reserved=0> thanks for the screenshot? Could you please clarify if this PR is supposed to add the feature you're proposing? Or are you trying to suggest we add the feature?
If the PR contains the implementation of the feature could you please rebase or merge master so that only you're changes are included in the diff? If this is for suggestion purposes then we can track the request through this issue #1713<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fsqlopsstudio%2Fissues%2F1713&data=02%7C01%7C%7C7579ecea4da545063ec408d5dad5955c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636655533219023159&sdata=zq6QM223TidD1RUIWOpj3V0keO9eM22r9Yj4HJK%2FMLk%3D&reserved=0>. Thanks!

**Comment by kburtram** [comment]
@grishRodCas thanks for confirming!  In this case, I'll close this PR now and we'll track the request in the active issue (we use the PRs to track proposed implementations).

**Pull request closed without merging**
