### PR TITLE
run query shortcut key alt+x added

### PR DESCRIPTION
**Pull request by yunuskiran**
in sql server management studio has shortcut key alt+x for run query. but there is no. i added that shortcut key

### CODE REVIEW

**Comment by anthonydresser** [comment]
I'm not sure what the value add here is. If you prefer a different keybinding you can edit the keybinding for all the different run queries we have.
image
If you want to have multiple keybindings for the same action, you can also modify the json directly and add another entry
image

**Comment by kburtram** [comment]
@anthonydresser I think the point of the PR is to try to make it easier for users moving from SSMS to SQL Ops Studio by making the keymap more familiar.  Since SSMS users are a large portion of our users I think there is some validity here.

Though I also agree that keymaps are user configurable so they can be customized as desired.  Also, if we continue to add multiple keymaps for each command we're going to start running out of intuitive shortcuts for new commands.

I think there may be some special cases where it makes since to have duplicate commands to ease adoption friction.  In general, I suspect it's more scalable to solve this problem through keymap extensions.

@yunuskiran I wonder if perhaps this keymap should be included in the SSMS Keymap for SQL Operations Studio extension at https://github.com/kevcunnane/ssmskeymap.  This extension is explicitly to provide shortcuts that will be familiar to SSMS users?

**Comment by yunuskiran** [comment]
Thats true. I didn't see this extension. I use ctrl+x in general. I will use that extension thanks for information.

**Comment by kburtram** [comment]
@yunuskiran I didn't see Alt-X in the current SSMS Keymap extension.  I'll follow-up with @kevcunnane to see if we can add this there.  Thanks for the PR!

**Pull request closed without merging**
