### PR TITLE
Fix #58: Default sort order for DB size widget

### LINKED ISSUE #58: Change default sort order for table-space-db-insight widget to desc
- SQL Operations Studio Version: sqlops 0.23.6
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:
 table-space-db-insight widget show first 10 database without desc order by size:
\resources\app\extensions\insights-default\sql\db_size.sql  - 
....
order by DataFileSizeMB **desc**

### PR DESCRIPTION
**Pull request by mwiedemeyer**
Change default sort order for the DB size widget to descending

### CODE REVIEW

**Comment by kburtram** [comment]
@erickangMSFT @kevcunnane could you take a look and make sure this makes sense.  Seems like a good fix to me.

**Comment by kburtram** [comment]
@mwiedemeyer fyi, this repo is a snapshot of our internal development repo with the source aligned with our current public release build.  In the next few months we plan to unify these repos so engineering will be done directly in the public repo.  For now, we'll manually port external pull requests back to the internal repo and they'll be included back when we do the next snapshot.  Unfortunately this may cause the commit history be be a little confusing in this repo.  When the internal repo is made public the commit history should be retained in a sensible way.  I'll add these details to the contribution wiki.

Also, for some reason the Contributor License Agreement bot didn't run on this PR.   There's a quick form we need filled out the first time we accept an external contribution from a community member.  There is an exception for PRs that only change a few lines of code, so I think we're good in this case.  I'll check on the bot configuration.

**Comment by mwiedemeyer** [comment]
@kburtram Hi, thanks for making it clear. FYI: For me, github shows that the cla check has been passed:
image

**Comment by kburtram** [comment]
@mwiedemeyer thanks for clarifying.  I think on our other repo there's a bot which adds labels to the PR.  That section works just as well.

fyi, a lot of the team will be on vacation next week, so there may be some slowness in responding on this PR.  I don't anticipate any issue getting this included in the Dec. release.

**Pull request merged**
