### PR TITLE
Add cursor snippet

### PR DESCRIPTION
**Pull request by SebastianPfliegel**
I thought adding a snippet for cursor declaration might be a good idea.

### CODE REVIEW

**Comment by kburtram** [comment]
@erickangMSFT please take a look at this PR.  Thanks!

**Comment by erickangMSFT** [comment]
@SebastianPfliegel @kburtram Sebastian, we just found that a query that returns many resultset crashes SQL Ops Studio while rendering many grids. Would it still make sense  with the select statement sample commented from the snippet to avoid accidental crashes until we fix the issue? In practice, users will replace the begin...end part but I am just concerning about accidental crash with a data / work in progress loss. 

WHILE @@FETCH_STATUS = 0
BEGIN
    -- add instructions to be executed for every row
    -- SELECT @Column1, @Column2
    -- FETCH NEXT FROM db_cursor INTO @Column1, @Column2
END

**Comment by kburtram** [comment]
Here's the issue for the product hang related to executing snippet https://github.com/Microsoft/sqlopsstudio/issues/480 on a table with a lot of rows.

**Comment by SebastianPfliegel** [comment]
As printing also may lead to hangs/crashes I decided to remove that bit and let the user decide what to place into it.

**Comment by erickangMSFT** [comment]
@SebastianPfliegel thanks Sebastian.

**Pull request merged**
